package com.chinasofti.projectDigest.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_application
 */
public class TApplication {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_application.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_application.field_id
	 * @mbg.generated
	 */
	private Integer fieldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_application.application
	 * @mbg.generated
	 */
	private String application;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_application.id
	 * @return  the value of t_application.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_application.id
	 * @param id  the value for t_application.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_application.field_id
	 * @return  the value of t_application.field_id
	 * @mbg.generated
	 */
	public Integer getFieldId() {
		return fieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_application.field_id
	 * @param fieldId  the value for t_application.field_id
	 * @mbg.generated
	 */
	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_application.application
	 * @return  the value of t_application.application
	 * @mbg.generated
	 */
	public String getApplication() {
		return application;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_application.application
	 * @param application  the value for t_application.application
	 * @mbg.generated
	 */
	public void setApplication(String application) {
		this.application = application == null ? null : application.trim();
	}
}