package com.chinasofti.projectDigest.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_field
 */
public class TField {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_field.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_field.industry_id
	 * @mbg.generated
	 */
	private Integer industryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_field.field
	 * @mbg.generated
	 */
	private String field;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_field.id
	 * @return  the value of t_field.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_field.id
	 * @param id  the value for t_field.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_field.industry_id
	 * @return  the value of t_field.industry_id
	 * @mbg.generated
	 */
	public Integer getIndustryId() {
		return industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_field.industry_id
	 * @param industryId  the value for t_field.industry_id
	 * @mbg.generated
	 */
	public void setIndustryId(Integer industryId) {
		this.industryId = industryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_field.field
	 * @return  the value of t_field.field
	 * @mbg.generated
	 */
	public String getField() {
		return field;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_field.field
	 * @param field  the value for t_field.field
	 * @mbg.generated
	 */
	public void setField(String field) {
		this.field = field == null ? null : field.trim();
	}
}