package com.chinasofti.projectDigest.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_menu
 */
public class TMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.text
	 * @mbg.generated
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.state
	 * @mbg.generated
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.pid
	 * @mbg.generated
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.iconCls
	 * @mbg.generated
	 */
	private String iconcls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_menu.icon_cls
	 * @mbg.generated
	 */
	private String iconCls;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.id
	 * @return  the value of t_menu.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.id
	 * @param id  the value for t_menu.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.text
	 * @return  the value of t_menu.text
	 * @mbg.generated
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.text
	 * @param text  the value for t_menu.text
	 * @mbg.generated
	 */
	public void setText(String text) {
		this.text = text == null ? null : text.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.state
	 * @return  the value of t_menu.state
	 * @mbg.generated
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.state
	 * @param state  the value for t_menu.state
	 * @mbg.generated
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.pid
	 * @return  the value of t_menu.pid
	 * @mbg.generated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.pid
	 * @param pid  the value for t_menu.pid
	 * @mbg.generated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.iconCls
	 * @return  the value of t_menu.iconCls
	 * @mbg.generated
	 */
	public String getIconcls() {
		return iconcls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.iconCls
	 * @param iconcls  the value for t_menu.iconCls
	 * @mbg.generated
	 */
	public void setIconcls(String iconcls) {
		this.iconcls = iconcls == null ? null : iconcls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.url
	 * @return  the value of t_menu.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.url
	 * @param url  the value for t_menu.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_menu.icon_cls
	 * @return  the value of t_menu.icon_cls
	 * @mbg.generated
	 */
	public String getIconCls() {
		return iconCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_menu.icon_cls
	 * @param iconCls  the value for t_menu.icon_cls
	 * @mbg.generated
	 */
	public void setIconCls(String iconCls) {
		this.iconCls = iconCls == null ? null : iconCls.trim();
	}
}