package com.chinasofti.projectDigest.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TProjdigestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public TProjdigestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIsNull() {
			addCriterion("proj_outcome_id is null");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIsNotNull() {
			addCriterion("proj_outcome_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdEqualTo(String value) {
			addCriterion("proj_outcome_id =", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotEqualTo(String value) {
			addCriterion("proj_outcome_id <>", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdGreaterThan(String value) {
			addCriterion("proj_outcome_id >", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdGreaterThanOrEqualTo(String value) {
			addCriterion("proj_outcome_id >=", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLessThan(String value) {
			addCriterion("proj_outcome_id <", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLessThanOrEqualTo(String value) {
			addCriterion("proj_outcome_id <=", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLike(String value) {
			addCriterion("proj_outcome_id like", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotLike(String value) {
			addCriterion("proj_outcome_id not like", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIn(List<String> values) {
			addCriterion("proj_outcome_id in", values, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotIn(List<String> values) {
			addCriterion("proj_outcome_id not in", values, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdBetween(String value1, String value2) {
			addCriterion("proj_outcome_id between", value1, value2, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotBetween(String value1, String value2) {
			addCriterion("proj_outcome_id not between", value1, value2, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andLobIsNull() {
			addCriterion("lob is null");
			return (Criteria) this;
		}

		public Criteria andLobIsNotNull() {
			addCriterion("lob is not null");
			return (Criteria) this;
		}

		public Criteria andLobEqualTo(String value) {
			addCriterion("lob =", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotEqualTo(String value) {
			addCriterion("lob <>", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThan(String value) {
			addCriterion("lob >", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThanOrEqualTo(String value) {
			addCriterion("lob >=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThan(String value) {
			addCriterion("lob <", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThanOrEqualTo(String value) {
			addCriterion("lob <=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLike(String value) {
			addCriterion("lob like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotLike(String value) {
			addCriterion("lob not like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobIn(List<String> values) {
			addCriterion("lob in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotIn(List<String> values) {
			addCriterion("lob not in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobBetween(String value1, String value2) {
			addCriterion("lob between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotBetween(String value1, String value2) {
			addCriterion("lob not between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andProjNameIsNull() {
			addCriterion("proj_name is null");
			return (Criteria) this;
		}

		public Criteria andProjNameIsNotNull() {
			addCriterion("proj_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjNameEqualTo(String value) {
			addCriterion("proj_name =", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotEqualTo(String value) {
			addCriterion("proj_name <>", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameGreaterThan(String value) {
			addCriterion("proj_name >", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameGreaterThanOrEqualTo(String value) {
			addCriterion("proj_name >=", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLessThan(String value) {
			addCriterion("proj_name <", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLessThanOrEqualTo(String value) {
			addCriterion("proj_name <=", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLike(String value) {
			addCriterion("proj_name like", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotLike(String value) {
			addCriterion("proj_name not like", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameIn(List<String> values) {
			addCriterion("proj_name in", values, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotIn(List<String> values) {
			addCriterion("proj_name not in", values, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameBetween(String value1, String value2) {
			addCriterion("proj_name between", value1, value2, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotBetween(String value1, String value2) {
			addCriterion("proj_name not between", value1, value2, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNumIsNull() {
			addCriterion("proj_num is null");
			return (Criteria) this;
		}

		public Criteria andProjNumIsNotNull() {
			addCriterion("proj_num is not null");
			return (Criteria) this;
		}

		public Criteria andProjNumEqualTo(String value) {
			addCriterion("proj_num =", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotEqualTo(String value) {
			addCriterion("proj_num <>", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumGreaterThan(String value) {
			addCriterion("proj_num >", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumGreaterThanOrEqualTo(String value) {
			addCriterion("proj_num >=", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLessThan(String value) {
			addCriterion("proj_num <", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLessThanOrEqualTo(String value) {
			addCriterion("proj_num <=", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLike(String value) {
			addCriterion("proj_num like", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotLike(String value) {
			addCriterion("proj_num not like", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumIn(List<String> values) {
			addCriterion("proj_num in", values, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotIn(List<String> values) {
			addCriterion("proj_num not in", values, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumBetween(String value1, String value2) {
			addCriterion("proj_num between", value1, value2, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotBetween(String value1, String value2) {
			addCriterion("proj_num not between", value1, value2, "projNum");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNull() {
			addCriterion("cust_name is null");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNotNull() {
			addCriterion("cust_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustNameEqualTo(String value) {
			addCriterion("cust_name =", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotEqualTo(String value) {
			addCriterion("cust_name <>", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThan(String value) {
			addCriterion("cust_name >", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_name >=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThan(String value) {
			addCriterion("cust_name <", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThanOrEqualTo(String value) {
			addCriterion("cust_name <=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLike(String value) {
			addCriterion("cust_name like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotLike(String value) {
			addCriterion("cust_name not like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameIn(List<String> values) {
			addCriterion("cust_name in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotIn(List<String> values) {
			addCriterion("cust_name not in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameBetween(String value1, String value2) {
			addCriterion("cust_name between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotBetween(String value1, String value2) {
			addCriterion("cust_name not between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andProjBriefIsNull() {
			addCriterion("proj_brief is null");
			return (Criteria) this;
		}

		public Criteria andProjBriefIsNotNull() {
			addCriterion("proj_brief is not null");
			return (Criteria) this;
		}

		public Criteria andProjBriefEqualTo(String value) {
			addCriterion("proj_brief =", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefNotEqualTo(String value) {
			addCriterion("proj_brief <>", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefGreaterThan(String value) {
			addCriterion("proj_brief >", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefGreaterThanOrEqualTo(String value) {
			addCriterion("proj_brief >=", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefLessThan(String value) {
			addCriterion("proj_brief <", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefLessThanOrEqualTo(String value) {
			addCriterion("proj_brief <=", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefLike(String value) {
			addCriterion("proj_brief like", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefNotLike(String value) {
			addCriterion("proj_brief not like", value, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefIn(List<String> values) {
			addCriterion("proj_brief in", values, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefNotIn(List<String> values) {
			addCriterion("proj_brief not in", values, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefBetween(String value1, String value2) {
			addCriterion("proj_brief between", value1, value2, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBriefNotBetween(String value1, String value2) {
			addCriterion("proj_brief not between", value1, value2, "projBrief");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIsNull() {
			addCriterion("proj_begin_date is null");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIsNotNull() {
			addCriterion("proj_begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateEqualTo(String value) {
			addCriterion("proj_begin_date =", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotEqualTo(String value) {
			addCriterion("proj_begin_date <>", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateGreaterThan(String value) {
			addCriterion("proj_begin_date >", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateGreaterThanOrEqualTo(String value) {
			addCriterion("proj_begin_date >=", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLessThan(String value) {
			addCriterion("proj_begin_date <", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLessThanOrEqualTo(String value) {
			addCriterion("proj_begin_date <=", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLike(String value) {
			addCriterion("proj_begin_date like", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotLike(String value) {
			addCriterion("proj_begin_date not like", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIn(List<String> values) {
			addCriterion("proj_begin_date in", values, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotIn(List<String> values) {
			addCriterion("proj_begin_date not in", values, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateBetween(String value1, String value2) {
			addCriterion("proj_begin_date between", value1, value2, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotBetween(String value1, String value2) {
			addCriterion("proj_begin_date not between", value1, value2, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIsNull() {
			addCriterion("proj_end_date is null");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIsNotNull() {
			addCriterion("proj_end_date is not null");
			return (Criteria) this;
		}

		public Criteria andProjEndDateEqualTo(String value) {
			addCriterion("proj_end_date =", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotEqualTo(String value) {
			addCriterion("proj_end_date <>", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateGreaterThan(String value) {
			addCriterion("proj_end_date >", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateGreaterThanOrEqualTo(String value) {
			addCriterion("proj_end_date >=", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLessThan(String value) {
			addCriterion("proj_end_date <", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLessThanOrEqualTo(String value) {
			addCriterion("proj_end_date <=", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLike(String value) {
			addCriterion("proj_end_date like", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotLike(String value) {
			addCriterion("proj_end_date not like", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIn(List<String> values) {
			addCriterion("proj_end_date in", values, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotIn(List<String> values) {
			addCriterion("proj_end_date not in", values, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateBetween(String value1, String value2) {
			addCriterion("proj_end_date between", value1, value2, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotBetween(String value1, String value2) {
			addCriterion("proj_end_date not between", value1, value2, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andArchivePathIsNull() {
			addCriterion("archive_path is null");
			return (Criteria) this;
		}

		public Criteria andArchivePathIsNotNull() {
			addCriterion("archive_path is not null");
			return (Criteria) this;
		}

		public Criteria andArchivePathEqualTo(String value) {
			addCriterion("archive_path =", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathNotEqualTo(String value) {
			addCriterion("archive_path <>", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathGreaterThan(String value) {
			addCriterion("archive_path >", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathGreaterThanOrEqualTo(String value) {
			addCriterion("archive_path >=", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathLessThan(String value) {
			addCriterion("archive_path <", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathLessThanOrEqualTo(String value) {
			addCriterion("archive_path <=", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathLike(String value) {
			addCriterion("archive_path like", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathNotLike(String value) {
			addCriterion("archive_path not like", value, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathIn(List<String> values) {
			addCriterion("archive_path in", values, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathNotIn(List<String> values) {
			addCriterion("archive_path not in", values, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathBetween(String value1, String value2) {
			addCriterion("archive_path between", value1, value2, "archivePath");
			return (Criteria) this;
		}

		public Criteria andArchivePathNotBetween(String value1, String value2) {
			addCriterion("archive_path not between", value1, value2, "archivePath");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIsNull() {
			addCriterion("proj_manager_name is null");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIsNotNull() {
			addCriterion("proj_manager_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameEqualTo(String value) {
			addCriterion("proj_manager_name =", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotEqualTo(String value) {
			addCriterion("proj_manager_name <>", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameGreaterThan(String value) {
			addCriterion("proj_manager_name >", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manager_name >=", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLessThan(String value) {
			addCriterion("proj_manager_name <", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLessThanOrEqualTo(String value) {
			addCriterion("proj_manager_name <=", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLike(String value) {
			addCriterion("proj_manager_name like", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotLike(String value) {
			addCriterion("proj_manager_name not like", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIn(List<String> values) {
			addCriterion("proj_manager_name in", values, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotIn(List<String> values) {
			addCriterion("proj_manager_name not in", values, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameBetween(String value1, String value2) {
			addCriterion("proj_manager_name between", value1, value2, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotBetween(String value1, String value2) {
			addCriterion("proj_manager_name not between", value1, value2, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIsNull() {
			addCriterion("proj_manage_id is null");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIsNotNull() {
			addCriterion("proj_manage_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageIdEqualTo(String value) {
			addCriterion("proj_manage_id =", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotEqualTo(String value) {
			addCriterion("proj_manage_id <>", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdGreaterThan(String value) {
			addCriterion("proj_manage_id >", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_id >=", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLessThan(String value) {
			addCriterion("proj_manage_id <", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_id <=", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLike(String value) {
			addCriterion("proj_manage_id like", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotLike(String value) {
			addCriterion("proj_manage_id not like", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIn(List<String> values) {
			addCriterion("proj_manage_id in", values, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotIn(List<String> values) {
			addCriterion("proj_manage_id not in", values, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdBetween(String value1, String value2) {
			addCriterion("proj_manage_id between", value1, value2, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotBetween(String value1, String value2) {
			addCriterion("proj_manage_id not between", value1, value2, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIsNull() {
			addCriterion("proj_manage_email is null");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIsNotNull() {
			addCriterion("proj_manage_email is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailEqualTo(String value) {
			addCriterion("proj_manage_email =", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotEqualTo(String value) {
			addCriterion("proj_manage_email <>", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailGreaterThan(String value) {
			addCriterion("proj_manage_email >", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_email >=", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLessThan(String value) {
			addCriterion("proj_manage_email <", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_email <=", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLike(String value) {
			addCriterion("proj_manage_email like", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotLike(String value) {
			addCriterion("proj_manage_email not like", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIn(List<String> values) {
			addCriterion("proj_manage_email in", values, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotIn(List<String> values) {
			addCriterion("proj_manage_email not in", values, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailBetween(String value1, String value2) {
			addCriterion("proj_manage_email between", value1, value2, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotBetween(String value1, String value2) {
			addCriterion("proj_manage_email not between", value1, value2, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIsNull() {
			addCriterion("proj_manage_tel is null");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIsNotNull() {
			addCriterion("proj_manage_tel is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageTelEqualTo(String value) {
			addCriterion("proj_manage_tel =", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotEqualTo(String value) {
			addCriterion("proj_manage_tel <>", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelGreaterThan(String value) {
			addCriterion("proj_manage_tel >", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_tel >=", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLessThan(String value) {
			addCriterion("proj_manage_tel <", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_tel <=", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLike(String value) {
			addCriterion("proj_manage_tel like", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotLike(String value) {
			addCriterion("proj_manage_tel not like", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIn(List<String> values) {
			addCriterion("proj_manage_tel in", values, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotIn(List<String> values) {
			addCriterion("proj_manage_tel not in", values, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelBetween(String value1, String value2) {
			addCriterion("proj_manage_tel between", value1, value2, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotBetween(String value1, String value2) {
			addCriterion("proj_manage_tel not between", value1, value2, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryIsNull() {
			addCriterion("industry_category is null");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryIsNotNull() {
			addCriterion("industry_category is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryEqualTo(String value) {
			addCriterion("industry_category =", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryNotEqualTo(String value) {
			addCriterion("industry_category <>", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryGreaterThan(String value) {
			addCriterion("industry_category >", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("industry_category >=", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryLessThan(String value) {
			addCriterion("industry_category <", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryLessThanOrEqualTo(String value) {
			addCriterion("industry_category <=", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryLike(String value) {
			addCriterion("industry_category like", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryNotLike(String value) {
			addCriterion("industry_category not like", value, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryIn(List<String> values) {
			addCriterion("industry_category in", values, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryNotIn(List<String> values) {
			addCriterion("industry_category not in", values, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryBetween(String value1, String value2) {
			addCriterion("industry_category between", value1, value2, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andIndustryCategoryNotBetween(String value1, String value2) {
			addCriterion("industry_category not between", value1, value2, "industryCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryIsNull() {
			addCriterion("field_category is null");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryIsNotNull() {
			addCriterion("field_category is not null");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryEqualTo(String value) {
			addCriterion("field_category =", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryNotEqualTo(String value) {
			addCriterion("field_category <>", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryGreaterThan(String value) {
			addCriterion("field_category >", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("field_category >=", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryLessThan(String value) {
			addCriterion("field_category <", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryLessThanOrEqualTo(String value) {
			addCriterion("field_category <=", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryLike(String value) {
			addCriterion("field_category like", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryNotLike(String value) {
			addCriterion("field_category not like", value, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryIn(List<String> values) {
			addCriterion("field_category in", values, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryNotIn(List<String> values) {
			addCriterion("field_category not in", values, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryBetween(String value1, String value2) {
			addCriterion("field_category between", value1, value2, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andFieldCategoryNotBetween(String value1, String value2) {
			addCriterion("field_category not between", value1, value2, "fieldCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryIsNull() {
			addCriterion("application_category is null");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryIsNotNull() {
			addCriterion("application_category is not null");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryEqualTo(String value) {
			addCriterion("application_category =", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryNotEqualTo(String value) {
			addCriterion("application_category <>", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryGreaterThan(String value) {
			addCriterion("application_category >", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("application_category >=", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryLessThan(String value) {
			addCriterion("application_category <", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryLessThanOrEqualTo(String value) {
			addCriterion("application_category <=", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryLike(String value) {
			addCriterion("application_category like", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryNotLike(String value) {
			addCriterion("application_category not like", value, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryIn(List<String> values) {
			addCriterion("application_category in", values, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryNotIn(List<String> values) {
			addCriterion("application_category not in", values, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryBetween(String value1, String value2) {
			addCriterion("application_category between", value1, value2, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andApplicationCategoryNotBetween(String value1, String value2) {
			addCriterion("application_category not between", value1, value2, "applicationCategory");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageIsNull() {
			addCriterion("used_language is null");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageIsNotNull() {
			addCriterion("used_language is not null");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageEqualTo(String value) {
			addCriterion("used_language =", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageNotEqualTo(String value) {
			addCriterion("used_language <>", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageGreaterThan(String value) {
			addCriterion("used_language >", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageGreaterThanOrEqualTo(String value) {
			addCriterion("used_language >=", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageLessThan(String value) {
			addCriterion("used_language <", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageLessThanOrEqualTo(String value) {
			addCriterion("used_language <=", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageLike(String value) {
			addCriterion("used_language like", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageNotLike(String value) {
			addCriterion("used_language not like", value, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageIn(List<String> values) {
			addCriterion("used_language in", values, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageNotIn(List<String> values) {
			addCriterion("used_language not in", values, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageBetween(String value1, String value2) {
			addCriterion("used_language between", value1, value2, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andUsedLanguageNotBetween(String value1, String value2) {
			addCriterion("used_language not between", value1, value2, "usedLanguage");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIsNull() {
			addCriterion("system_soft is null");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIsNotNull() {
			addCriterion("system_soft is not null");
			return (Criteria) this;
		}

		public Criteria andSystemSoftEqualTo(String value) {
			addCriterion("system_soft =", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotEqualTo(String value) {
			addCriterion("system_soft <>", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftGreaterThan(String value) {
			addCriterion("system_soft >", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftGreaterThanOrEqualTo(String value) {
			addCriterion("system_soft >=", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLessThan(String value) {
			addCriterion("system_soft <", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLessThanOrEqualTo(String value) {
			addCriterion("system_soft <=", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLike(String value) {
			addCriterion("system_soft like", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotLike(String value) {
			addCriterion("system_soft not like", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIn(List<String> values) {
			addCriterion("system_soft in", values, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotIn(List<String> values) {
			addCriterion("system_soft not in", values, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftBetween(String value1, String value2) {
			addCriterion("system_soft between", value1, value2, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotBetween(String value1, String value2) {
			addCriterion("system_soft not between", value1, value2, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemHardIsNull() {
			addCriterion("system_hard is null");
			return (Criteria) this;
		}

		public Criteria andSystemHardIsNotNull() {
			addCriterion("system_hard is not null");
			return (Criteria) this;
		}

		public Criteria andSystemHardEqualTo(String value) {
			addCriterion("system_hard =", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotEqualTo(String value) {
			addCriterion("system_hard <>", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardGreaterThan(String value) {
			addCriterion("system_hard >", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardGreaterThanOrEqualTo(String value) {
			addCriterion("system_hard >=", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLessThan(String value) {
			addCriterion("system_hard <", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLessThanOrEqualTo(String value) {
			addCriterion("system_hard <=", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLike(String value) {
			addCriterion("system_hard like", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotLike(String value) {
			addCriterion("system_hard not like", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardIn(List<String> values) {
			addCriterion("system_hard in", values, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotIn(List<String> values) {
			addCriterion("system_hard not in", values, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardBetween(String value1, String value2) {
			addCriterion("system_hard between", value1, value2, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotBetween(String value1, String value2) {
			addCriterion("system_hard not between", value1, value2, "systemHard");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseIsNull() {
			addCriterion("used_database is null");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseIsNotNull() {
			addCriterion("used_database is not null");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseEqualTo(String value) {
			addCriterion("used_database =", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseNotEqualTo(String value) {
			addCriterion("used_database <>", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseGreaterThan(String value) {
			addCriterion("used_database >", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseGreaterThanOrEqualTo(String value) {
			addCriterion("used_database >=", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseLessThan(String value) {
			addCriterion("used_database <", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseLessThanOrEqualTo(String value) {
			addCriterion("used_database <=", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseLike(String value) {
			addCriterion("used_database like", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseNotLike(String value) {
			addCriterion("used_database not like", value, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseIn(List<String> values) {
			addCriterion("used_database in", values, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseNotIn(List<String> values) {
			addCriterion("used_database not in", values, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseBetween(String value1, String value2) {
			addCriterion("used_database between", value1, value2, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andUsedDatabaseNotBetween(String value1, String value2) {
			addCriterion("used_database not between", value1, value2, "usedDatabase");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkIsNull() {
			addCriterion("test_framework is null");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkIsNotNull() {
			addCriterion("test_framework is not null");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkEqualTo(String value) {
			addCriterion("test_framework =", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkNotEqualTo(String value) {
			addCriterion("test_framework <>", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkGreaterThan(String value) {
			addCriterion("test_framework >", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkGreaterThanOrEqualTo(String value) {
			addCriterion("test_framework >=", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkLessThan(String value) {
			addCriterion("test_framework <", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkLessThanOrEqualTo(String value) {
			addCriterion("test_framework <=", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkLike(String value) {
			addCriterion("test_framework like", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkNotLike(String value) {
			addCriterion("test_framework not like", value, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkIn(List<String> values) {
			addCriterion("test_framework in", values, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkNotIn(List<String> values) {
			addCriterion("test_framework not in", values, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkBetween(String value1, String value2) {
			addCriterion("test_framework between", value1, value2, "testFramework");
			return (Criteria) this;
		}

		public Criteria andTestFrameworkNotBetween(String value1, String value2) {
			addCriterion("test_framework not between", value1, value2, "testFramework");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIsNull() {
			addCriterion("key_tech_skills is null");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIsNotNull() {
			addCriterion("key_tech_skills is not null");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsEqualTo(String value) {
			addCriterion("key_tech_skills =", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotEqualTo(String value) {
			addCriterion("key_tech_skills <>", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsGreaterThan(String value) {
			addCriterion("key_tech_skills >", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsGreaterThanOrEqualTo(String value) {
			addCriterion("key_tech_skills >=", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLessThan(String value) {
			addCriterion("key_tech_skills <", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLessThanOrEqualTo(String value) {
			addCriterion("key_tech_skills <=", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLike(String value) {
			addCriterion("key_tech_skills like", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotLike(String value) {
			addCriterion("key_tech_skills not like", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIn(List<String> values) {
			addCriterion("key_tech_skills in", values, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotIn(List<String> values) {
			addCriterion("key_tech_skills not in", values, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsBetween(String value1, String value2) {
			addCriterion("key_tech_skills between", value1, value2, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotBetween(String value1, String value2) {
			addCriterion("key_tech_skills not between", value1, value2, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andIsImportIsNull() {
			addCriterion("is_import is null");
			return (Criteria) this;
		}

		public Criteria andIsImportIsNotNull() {
			addCriterion("is_import is not null");
			return (Criteria) this;
		}

		public Criteria andIsImportEqualTo(String value) {
			addCriterion("is_import =", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportNotEqualTo(String value) {
			addCriterion("is_import <>", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportGreaterThan(String value) {
			addCriterion("is_import >", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportGreaterThanOrEqualTo(String value) {
			addCriterion("is_import >=", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportLessThan(String value) {
			addCriterion("is_import <", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportLessThanOrEqualTo(String value) {
			addCriterion("is_import <=", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportLike(String value) {
			addCriterion("is_import like", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportNotLike(String value) {
			addCriterion("is_import not like", value, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportIn(List<String> values) {
			addCriterion("is_import in", values, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportNotIn(List<String> values) {
			addCriterion("is_import not in", values, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportBetween(String value1, String value2) {
			addCriterion("is_import between", value1, value2, "isImport");
			return (Criteria) this;
		}

		public Criteria andIsImportNotBetween(String value1, String value2) {
			addCriterion("is_import not between", value1, value2, "isImport");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_projdigest
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_projdigest
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}