package com.chinasofti.projectDigest.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_projdigest_old
 */
public class TProjdigestOld {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_outcome_id
	 * @mbg.generated
	 */
	private String projOutcomeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.lob
	 * @mbg.generated
	 */
	private String lob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_name
	 * @mbg.generated
	 */
	private String projName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_num
	 * @mbg.generated
	 */
	private String projNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.cust_name
	 * @mbg.generated
	 */
	private String custName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.relate_proj_name1
	 * @mbg.generated
	 */
	private String relateProjName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.relate_proj_name2
	 * @mbg.generated
	 */
	private String relateProjName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.relate_proj_name3
	 * @mbg.generated
	 */
	private String relateProjName3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.subcontract_state
	 * @mbg.generated
	 */
	private String subcontractState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_manager_name
	 * @mbg.generated
	 */
	private String projManagerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_manage_id
	 * @mbg.generated
	 */
	private String projManageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_manage_email
	 * @mbg.generated
	 */
	private String projManageEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_manage_tel
	 * @mbg.generated
	 */
	private String projManageTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_manager_director_name
	 * @mbg.generated
	 */
	private String projManagerDirectorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_backbone1
	 * @mbg.generated
	 */
	private String projBackbone1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_backbone2
	 * @mbg.generated
	 */
	private String projBackbone2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_backbone3
	 * @mbg.generated
	 */
	private String projBackbone3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_begin_date
	 * @mbg.generated
	 */
	private String projBeginDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_end_date
	 * @mbg.generated
	 */
	private String projEndDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.input_date
	 * @mbg.generated
	 */
	private String inputDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_state
	 * @mbg.generated
	 */
	private String projState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.business_tech_key1
	 * @mbg.generated
	 */
	private String businessTechKey1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.business_tech_key2
	 * @mbg.generated
	 */
	private String businessTechKey2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.business_tech_key3
	 * @mbg.generated
	 */
	private String businessTechKey3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.business_brief
	 * @mbg.generated
	 */
	private String businessBrief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.business_func
	 * @mbg.generated
	 */
	private String businessFunc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.performance_index
	 * @mbg.generated
	 */
	private String performanceIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.system_soft
	 * @mbg.generated
	 */
	private String systemSoft;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.system_hard
	 * @mbg.generated
	 */
	private String systemHard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.system_architec
	 * @mbg.generated
	 */
	private String systemArchitec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.relavent_standard
	 * @mbg.generated
	 */
	private String relaventStandard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.key_tech_skills
	 * @mbg.generated
	 */
	private String keyTechSkills;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.usetools
	 * @mbg.generated
	 */
	private String usetools;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.remaining_prob
	 * @mbg.generated
	 */
	private String remainingProb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.market_competi
	 * @mbg.generated
	 */
	private String marketCompeti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.constraint_depend
	 * @mbg.generated
	 */
	private String constraintDepend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_projdigest_old.proj_back_bone3
	 * @mbg.generated
	 */
	private String projBackBone3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.id
	 * @return  the value of t_projdigest_old.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.id
	 * @param id  the value for t_projdigest_old.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_outcome_id
	 * @return  the value of t_projdigest_old.proj_outcome_id
	 * @mbg.generated
	 */
	public String getProjOutcomeId() {
		return projOutcomeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_outcome_id
	 * @param projOutcomeId  the value for t_projdigest_old.proj_outcome_id
	 * @mbg.generated
	 */
	public void setProjOutcomeId(String projOutcomeId) {
		this.projOutcomeId = projOutcomeId == null ? null : projOutcomeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.lob
	 * @return  the value of t_projdigest_old.lob
	 * @mbg.generated
	 */
	public String getLob() {
		return lob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.lob
	 * @param lob  the value for t_projdigest_old.lob
	 * @mbg.generated
	 */
	public void setLob(String lob) {
		this.lob = lob == null ? null : lob.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_name
	 * @return  the value of t_projdigest_old.proj_name
	 * @mbg.generated
	 */
	public String getProjName() {
		return projName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_name
	 * @param projName  the value for t_projdigest_old.proj_name
	 * @mbg.generated
	 */
	public void setProjName(String projName) {
		this.projName = projName == null ? null : projName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_num
	 * @return  the value of t_projdigest_old.proj_num
	 * @mbg.generated
	 */
	public String getProjNum() {
		return projNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_num
	 * @param projNum  the value for t_projdigest_old.proj_num
	 * @mbg.generated
	 */
	public void setProjNum(String projNum) {
		this.projNum = projNum == null ? null : projNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.cust_name
	 * @return  the value of t_projdigest_old.cust_name
	 * @mbg.generated
	 */
	public String getCustName() {
		return custName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.cust_name
	 * @param custName  the value for t_projdigest_old.cust_name
	 * @mbg.generated
	 */
	public void setCustName(String custName) {
		this.custName = custName == null ? null : custName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.relate_proj_name1
	 * @return  the value of t_projdigest_old.relate_proj_name1
	 * @mbg.generated
	 */
	public String getRelateProjName1() {
		return relateProjName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.relate_proj_name1
	 * @param relateProjName1  the value for t_projdigest_old.relate_proj_name1
	 * @mbg.generated
	 */
	public void setRelateProjName1(String relateProjName1) {
		this.relateProjName1 = relateProjName1 == null ? null : relateProjName1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.relate_proj_name2
	 * @return  the value of t_projdigest_old.relate_proj_name2
	 * @mbg.generated
	 */
	public String getRelateProjName2() {
		return relateProjName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.relate_proj_name2
	 * @param relateProjName2  the value for t_projdigest_old.relate_proj_name2
	 * @mbg.generated
	 */
	public void setRelateProjName2(String relateProjName2) {
		this.relateProjName2 = relateProjName2 == null ? null : relateProjName2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.relate_proj_name3
	 * @return  the value of t_projdigest_old.relate_proj_name3
	 * @mbg.generated
	 */
	public String getRelateProjName3() {
		return relateProjName3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.relate_proj_name3
	 * @param relateProjName3  the value for t_projdigest_old.relate_proj_name3
	 * @mbg.generated
	 */
	public void setRelateProjName3(String relateProjName3) {
		this.relateProjName3 = relateProjName3 == null ? null : relateProjName3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.subcontract_state
	 * @return  the value of t_projdigest_old.subcontract_state
	 * @mbg.generated
	 */
	public String getSubcontractState() {
		return subcontractState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.subcontract_state
	 * @param subcontractState  the value for t_projdigest_old.subcontract_state
	 * @mbg.generated
	 */
	public void setSubcontractState(String subcontractState) {
		this.subcontractState = subcontractState == null ? null : subcontractState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_manager_name
	 * @return  the value of t_projdigest_old.proj_manager_name
	 * @mbg.generated
	 */
	public String getProjManagerName() {
		return projManagerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_manager_name
	 * @param projManagerName  the value for t_projdigest_old.proj_manager_name
	 * @mbg.generated
	 */
	public void setProjManagerName(String projManagerName) {
		this.projManagerName = projManagerName == null ? null : projManagerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_manage_id
	 * @return  the value of t_projdigest_old.proj_manage_id
	 * @mbg.generated
	 */
	public String getProjManageId() {
		return projManageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_manage_id
	 * @param projManageId  the value for t_projdigest_old.proj_manage_id
	 * @mbg.generated
	 */
	public void setProjManageId(String projManageId) {
		this.projManageId = projManageId == null ? null : projManageId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_manage_email
	 * @return  the value of t_projdigest_old.proj_manage_email
	 * @mbg.generated
	 */
	public String getProjManageEmail() {
		return projManageEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_manage_email
	 * @param projManageEmail  the value for t_projdigest_old.proj_manage_email
	 * @mbg.generated
	 */
	public void setProjManageEmail(String projManageEmail) {
		this.projManageEmail = projManageEmail == null ? null : projManageEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_manage_tel
	 * @return  the value of t_projdigest_old.proj_manage_tel
	 * @mbg.generated
	 */
	public String getProjManageTel() {
		return projManageTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_manage_tel
	 * @param projManageTel  the value for t_projdigest_old.proj_manage_tel
	 * @mbg.generated
	 */
	public void setProjManageTel(String projManageTel) {
		this.projManageTel = projManageTel == null ? null : projManageTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_manager_director_name
	 * @return  the value of t_projdigest_old.proj_manager_director_name
	 * @mbg.generated
	 */
	public String getProjManagerDirectorName() {
		return projManagerDirectorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_manager_director_name
	 * @param projManagerDirectorName  the value for t_projdigest_old.proj_manager_director_name
	 * @mbg.generated
	 */
	public void setProjManagerDirectorName(String projManagerDirectorName) {
		this.projManagerDirectorName = projManagerDirectorName == null ? null : projManagerDirectorName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_backbone1
	 * @return  the value of t_projdigest_old.proj_backbone1
	 * @mbg.generated
	 */
	public String getProjBackbone1() {
		return projBackbone1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_backbone1
	 * @param projBackbone1  the value for t_projdigest_old.proj_backbone1
	 * @mbg.generated
	 */
	public void setProjBackbone1(String projBackbone1) {
		this.projBackbone1 = projBackbone1 == null ? null : projBackbone1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_backbone2
	 * @return  the value of t_projdigest_old.proj_backbone2
	 * @mbg.generated
	 */
	public String getProjBackbone2() {
		return projBackbone2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_backbone2
	 * @param projBackbone2  the value for t_projdigest_old.proj_backbone2
	 * @mbg.generated
	 */
	public void setProjBackbone2(String projBackbone2) {
		this.projBackbone2 = projBackbone2 == null ? null : projBackbone2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_backbone3
	 * @return  the value of t_projdigest_old.proj_backbone3
	 * @mbg.generated
	 */
	public String getProjBackbone3() {
		return projBackbone3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_backbone3
	 * @param projBackbone3  the value for t_projdigest_old.proj_backbone3
	 * @mbg.generated
	 */
	public void setProjBackbone3(String projBackbone3) {
		this.projBackbone3 = projBackbone3 == null ? null : projBackbone3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_begin_date
	 * @return  the value of t_projdigest_old.proj_begin_date
	 * @mbg.generated
	 */
	public String getProjBeginDate() {
		return projBeginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_begin_date
	 * @param projBeginDate  the value for t_projdigest_old.proj_begin_date
	 * @mbg.generated
	 */
	public void setProjBeginDate(String projBeginDate) {
		this.projBeginDate = projBeginDate == null ? null : projBeginDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_end_date
	 * @return  the value of t_projdigest_old.proj_end_date
	 * @mbg.generated
	 */
	public String getProjEndDate() {
		return projEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_end_date
	 * @param projEndDate  the value for t_projdigest_old.proj_end_date
	 * @mbg.generated
	 */
	public void setProjEndDate(String projEndDate) {
		this.projEndDate = projEndDate == null ? null : projEndDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.input_date
	 * @return  the value of t_projdigest_old.input_date
	 * @mbg.generated
	 */
	public String getInputDate() {
		return inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.input_date
	 * @param inputDate  the value for t_projdigest_old.input_date
	 * @mbg.generated
	 */
	public void setInputDate(String inputDate) {
		this.inputDate = inputDate == null ? null : inputDate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_state
	 * @return  the value of t_projdigest_old.proj_state
	 * @mbg.generated
	 */
	public String getProjState() {
		return projState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_state
	 * @param projState  the value for t_projdigest_old.proj_state
	 * @mbg.generated
	 */
	public void setProjState(String projState) {
		this.projState = projState == null ? null : projState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.business_tech_key1
	 * @return  the value of t_projdigest_old.business_tech_key1
	 * @mbg.generated
	 */
	public String getBusinessTechKey1() {
		return businessTechKey1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.business_tech_key1
	 * @param businessTechKey1  the value for t_projdigest_old.business_tech_key1
	 * @mbg.generated
	 */
	public void setBusinessTechKey1(String businessTechKey1) {
		this.businessTechKey1 = businessTechKey1 == null ? null : businessTechKey1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.business_tech_key2
	 * @return  the value of t_projdigest_old.business_tech_key2
	 * @mbg.generated
	 */
	public String getBusinessTechKey2() {
		return businessTechKey2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.business_tech_key2
	 * @param businessTechKey2  the value for t_projdigest_old.business_tech_key2
	 * @mbg.generated
	 */
	public void setBusinessTechKey2(String businessTechKey2) {
		this.businessTechKey2 = businessTechKey2 == null ? null : businessTechKey2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.business_tech_key3
	 * @return  the value of t_projdigest_old.business_tech_key3
	 * @mbg.generated
	 */
	public String getBusinessTechKey3() {
		return businessTechKey3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.business_tech_key3
	 * @param businessTechKey3  the value for t_projdigest_old.business_tech_key3
	 * @mbg.generated
	 */
	public void setBusinessTechKey3(String businessTechKey3) {
		this.businessTechKey3 = businessTechKey3 == null ? null : businessTechKey3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.business_brief
	 * @return  the value of t_projdigest_old.business_brief
	 * @mbg.generated
	 */
	public String getBusinessBrief() {
		return businessBrief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.business_brief
	 * @param businessBrief  the value for t_projdigest_old.business_brief
	 * @mbg.generated
	 */
	public void setBusinessBrief(String businessBrief) {
		this.businessBrief = businessBrief == null ? null : businessBrief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.business_func
	 * @return  the value of t_projdigest_old.business_func
	 * @mbg.generated
	 */
	public String getBusinessFunc() {
		return businessFunc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.business_func
	 * @param businessFunc  the value for t_projdigest_old.business_func
	 * @mbg.generated
	 */
	public void setBusinessFunc(String businessFunc) {
		this.businessFunc = businessFunc == null ? null : businessFunc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.performance_index
	 * @return  the value of t_projdigest_old.performance_index
	 * @mbg.generated
	 */
	public String getPerformanceIndex() {
		return performanceIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.performance_index
	 * @param performanceIndex  the value for t_projdigest_old.performance_index
	 * @mbg.generated
	 */
	public void setPerformanceIndex(String performanceIndex) {
		this.performanceIndex = performanceIndex == null ? null : performanceIndex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.system_soft
	 * @return  the value of t_projdigest_old.system_soft
	 * @mbg.generated
	 */
	public String getSystemSoft() {
		return systemSoft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.system_soft
	 * @param systemSoft  the value for t_projdigest_old.system_soft
	 * @mbg.generated
	 */
	public void setSystemSoft(String systemSoft) {
		this.systemSoft = systemSoft == null ? null : systemSoft.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.system_hard
	 * @return  the value of t_projdigest_old.system_hard
	 * @mbg.generated
	 */
	public String getSystemHard() {
		return systemHard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.system_hard
	 * @param systemHard  the value for t_projdigest_old.system_hard
	 * @mbg.generated
	 */
	public void setSystemHard(String systemHard) {
		this.systemHard = systemHard == null ? null : systemHard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.system_architec
	 * @return  the value of t_projdigest_old.system_architec
	 * @mbg.generated
	 */
	public String getSystemArchitec() {
		return systemArchitec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.system_architec
	 * @param systemArchitec  the value for t_projdigest_old.system_architec
	 * @mbg.generated
	 */
	public void setSystemArchitec(String systemArchitec) {
		this.systemArchitec = systemArchitec == null ? null : systemArchitec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.relavent_standard
	 * @return  the value of t_projdigest_old.relavent_standard
	 * @mbg.generated
	 */
	public String getRelaventStandard() {
		return relaventStandard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.relavent_standard
	 * @param relaventStandard  the value for t_projdigest_old.relavent_standard
	 * @mbg.generated
	 */
	public void setRelaventStandard(String relaventStandard) {
		this.relaventStandard = relaventStandard == null ? null : relaventStandard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.key_tech_skills
	 * @return  the value of t_projdigest_old.key_tech_skills
	 * @mbg.generated
	 */
	public String getKeyTechSkills() {
		return keyTechSkills;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.key_tech_skills
	 * @param keyTechSkills  the value for t_projdigest_old.key_tech_skills
	 * @mbg.generated
	 */
	public void setKeyTechSkills(String keyTechSkills) {
		this.keyTechSkills = keyTechSkills == null ? null : keyTechSkills.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.usetools
	 * @return  the value of t_projdigest_old.usetools
	 * @mbg.generated
	 */
	public String getUsetools() {
		return usetools;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.usetools
	 * @param usetools  the value for t_projdigest_old.usetools
	 * @mbg.generated
	 */
	public void setUsetools(String usetools) {
		this.usetools = usetools == null ? null : usetools.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.remaining_prob
	 * @return  the value of t_projdigest_old.remaining_prob
	 * @mbg.generated
	 */
	public String getRemainingProb() {
		return remainingProb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.remaining_prob
	 * @param remainingProb  the value for t_projdigest_old.remaining_prob
	 * @mbg.generated
	 */
	public void setRemainingProb(String remainingProb) {
		this.remainingProb = remainingProb == null ? null : remainingProb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.market_competi
	 * @return  the value of t_projdigest_old.market_competi
	 * @mbg.generated
	 */
	public String getMarketCompeti() {
		return marketCompeti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.market_competi
	 * @param marketCompeti  the value for t_projdigest_old.market_competi
	 * @mbg.generated
	 */
	public void setMarketCompeti(String marketCompeti) {
		this.marketCompeti = marketCompeti == null ? null : marketCompeti.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.constraint_depend
	 * @return  the value of t_projdigest_old.constraint_depend
	 * @mbg.generated
	 */
	public String getConstraintDepend() {
		return constraintDepend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.constraint_depend
	 * @param constraintDepend  the value for t_projdigest_old.constraint_depend
	 * @mbg.generated
	 */
	public void setConstraintDepend(String constraintDepend) {
		this.constraintDepend = constraintDepend == null ? null : constraintDepend.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_projdigest_old.proj_back_bone3
	 * @return  the value of t_projdigest_old.proj_back_bone3
	 * @mbg.generated
	 */
	public String getProjBackBone3() {
		return projBackBone3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_projdigest_old.proj_back_bone3
	 * @param projBackBone3  the value for t_projdigest_old.proj_back_bone3
	 * @mbg.generated
	 */
	public void setProjBackBone3(String projBackBone3) {
		this.projBackBone3 = projBackBone3 == null ? null : projBackBone3.trim();
	}
}