package com.chinasofti.projectDigest.pojo;

import java.util.ArrayList;
import java.util.List;

public class TProjdigestOldExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public TProjdigestOldExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIsNull() {
			addCriterion("proj_outcome_id is null");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIsNotNull() {
			addCriterion("proj_outcome_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdEqualTo(String value) {
			addCriterion("proj_outcome_id =", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotEqualTo(String value) {
			addCriterion("proj_outcome_id <>", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdGreaterThan(String value) {
			addCriterion("proj_outcome_id >", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdGreaterThanOrEqualTo(String value) {
			addCriterion("proj_outcome_id >=", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLessThan(String value) {
			addCriterion("proj_outcome_id <", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLessThanOrEqualTo(String value) {
			addCriterion("proj_outcome_id <=", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdLike(String value) {
			addCriterion("proj_outcome_id like", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotLike(String value) {
			addCriterion("proj_outcome_id not like", value, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdIn(List<String> values) {
			addCriterion("proj_outcome_id in", values, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotIn(List<String> values) {
			addCriterion("proj_outcome_id not in", values, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdBetween(String value1, String value2) {
			addCriterion("proj_outcome_id between", value1, value2, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andProjOutcomeIdNotBetween(String value1, String value2) {
			addCriterion("proj_outcome_id not between", value1, value2, "projOutcomeId");
			return (Criteria) this;
		}

		public Criteria andLobIsNull() {
			addCriterion("lob is null");
			return (Criteria) this;
		}

		public Criteria andLobIsNotNull() {
			addCriterion("lob is not null");
			return (Criteria) this;
		}

		public Criteria andLobEqualTo(String value) {
			addCriterion("lob =", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotEqualTo(String value) {
			addCriterion("lob <>", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThan(String value) {
			addCriterion("lob >", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobGreaterThanOrEqualTo(String value) {
			addCriterion("lob >=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThan(String value) {
			addCriterion("lob <", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLessThanOrEqualTo(String value) {
			addCriterion("lob <=", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobLike(String value) {
			addCriterion("lob like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotLike(String value) {
			addCriterion("lob not like", value, "lob");
			return (Criteria) this;
		}

		public Criteria andLobIn(List<String> values) {
			addCriterion("lob in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotIn(List<String> values) {
			addCriterion("lob not in", values, "lob");
			return (Criteria) this;
		}

		public Criteria andLobBetween(String value1, String value2) {
			addCriterion("lob between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andLobNotBetween(String value1, String value2) {
			addCriterion("lob not between", value1, value2, "lob");
			return (Criteria) this;
		}

		public Criteria andProjNameIsNull() {
			addCriterion("proj_name is null");
			return (Criteria) this;
		}

		public Criteria andProjNameIsNotNull() {
			addCriterion("proj_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjNameEqualTo(String value) {
			addCriterion("proj_name =", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotEqualTo(String value) {
			addCriterion("proj_name <>", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameGreaterThan(String value) {
			addCriterion("proj_name >", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameGreaterThanOrEqualTo(String value) {
			addCriterion("proj_name >=", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLessThan(String value) {
			addCriterion("proj_name <", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLessThanOrEqualTo(String value) {
			addCriterion("proj_name <=", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameLike(String value) {
			addCriterion("proj_name like", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotLike(String value) {
			addCriterion("proj_name not like", value, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameIn(List<String> values) {
			addCriterion("proj_name in", values, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotIn(List<String> values) {
			addCriterion("proj_name not in", values, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameBetween(String value1, String value2) {
			addCriterion("proj_name between", value1, value2, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNameNotBetween(String value1, String value2) {
			addCriterion("proj_name not between", value1, value2, "projName");
			return (Criteria) this;
		}

		public Criteria andProjNumIsNull() {
			addCriterion("proj_num is null");
			return (Criteria) this;
		}

		public Criteria andProjNumIsNotNull() {
			addCriterion("proj_num is not null");
			return (Criteria) this;
		}

		public Criteria andProjNumEqualTo(String value) {
			addCriterion("proj_num =", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotEqualTo(String value) {
			addCriterion("proj_num <>", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumGreaterThan(String value) {
			addCriterion("proj_num >", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumGreaterThanOrEqualTo(String value) {
			addCriterion("proj_num >=", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLessThan(String value) {
			addCriterion("proj_num <", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLessThanOrEqualTo(String value) {
			addCriterion("proj_num <=", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumLike(String value) {
			addCriterion("proj_num like", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotLike(String value) {
			addCriterion("proj_num not like", value, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumIn(List<String> values) {
			addCriterion("proj_num in", values, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotIn(List<String> values) {
			addCriterion("proj_num not in", values, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumBetween(String value1, String value2) {
			addCriterion("proj_num between", value1, value2, "projNum");
			return (Criteria) this;
		}

		public Criteria andProjNumNotBetween(String value1, String value2) {
			addCriterion("proj_num not between", value1, value2, "projNum");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNull() {
			addCriterion("cust_name is null");
			return (Criteria) this;
		}

		public Criteria andCustNameIsNotNull() {
			addCriterion("cust_name is not null");
			return (Criteria) this;
		}

		public Criteria andCustNameEqualTo(String value) {
			addCriterion("cust_name =", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotEqualTo(String value) {
			addCriterion("cust_name <>", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThan(String value) {
			addCriterion("cust_name >", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameGreaterThanOrEqualTo(String value) {
			addCriterion("cust_name >=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThan(String value) {
			addCriterion("cust_name <", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLessThanOrEqualTo(String value) {
			addCriterion("cust_name <=", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameLike(String value) {
			addCriterion("cust_name like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotLike(String value) {
			addCriterion("cust_name not like", value, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameIn(List<String> values) {
			addCriterion("cust_name in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotIn(List<String> values) {
			addCriterion("cust_name not in", values, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameBetween(String value1, String value2) {
			addCriterion("cust_name between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andCustNameNotBetween(String value1, String value2) {
			addCriterion("cust_name not between", value1, value2, "custName");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1IsNull() {
			addCriterion("relate_proj_name1 is null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1IsNotNull() {
			addCriterion("relate_proj_name1 is not null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1EqualTo(String value) {
			addCriterion("relate_proj_name1 =", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1NotEqualTo(String value) {
			addCriterion("relate_proj_name1 <>", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1GreaterThan(String value) {
			addCriterion("relate_proj_name1 >", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1GreaterThanOrEqualTo(String value) {
			addCriterion("relate_proj_name1 >=", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1LessThan(String value) {
			addCriterion("relate_proj_name1 <", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1LessThanOrEqualTo(String value) {
			addCriterion("relate_proj_name1 <=", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1Like(String value) {
			addCriterion("relate_proj_name1 like", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1NotLike(String value) {
			addCriterion("relate_proj_name1 not like", value, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1In(List<String> values) {
			addCriterion("relate_proj_name1 in", values, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1NotIn(List<String> values) {
			addCriterion("relate_proj_name1 not in", values, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1Between(String value1, String value2) {
			addCriterion("relate_proj_name1 between", value1, value2, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName1NotBetween(String value1, String value2) {
			addCriterion("relate_proj_name1 not between", value1, value2, "relateProjName1");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2IsNull() {
			addCriterion("relate_proj_name2 is null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2IsNotNull() {
			addCriterion("relate_proj_name2 is not null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2EqualTo(String value) {
			addCriterion("relate_proj_name2 =", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2NotEqualTo(String value) {
			addCriterion("relate_proj_name2 <>", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2GreaterThan(String value) {
			addCriterion("relate_proj_name2 >", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2GreaterThanOrEqualTo(String value) {
			addCriterion("relate_proj_name2 >=", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2LessThan(String value) {
			addCriterion("relate_proj_name2 <", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2LessThanOrEqualTo(String value) {
			addCriterion("relate_proj_name2 <=", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2Like(String value) {
			addCriterion("relate_proj_name2 like", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2NotLike(String value) {
			addCriterion("relate_proj_name2 not like", value, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2In(List<String> values) {
			addCriterion("relate_proj_name2 in", values, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2NotIn(List<String> values) {
			addCriterion("relate_proj_name2 not in", values, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2Between(String value1, String value2) {
			addCriterion("relate_proj_name2 between", value1, value2, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName2NotBetween(String value1, String value2) {
			addCriterion("relate_proj_name2 not between", value1, value2, "relateProjName2");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3IsNull() {
			addCriterion("relate_proj_name3 is null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3IsNotNull() {
			addCriterion("relate_proj_name3 is not null");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3EqualTo(String value) {
			addCriterion("relate_proj_name3 =", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3NotEqualTo(String value) {
			addCriterion("relate_proj_name3 <>", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3GreaterThan(String value) {
			addCriterion("relate_proj_name3 >", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3GreaterThanOrEqualTo(String value) {
			addCriterion("relate_proj_name3 >=", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3LessThan(String value) {
			addCriterion("relate_proj_name3 <", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3LessThanOrEqualTo(String value) {
			addCriterion("relate_proj_name3 <=", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3Like(String value) {
			addCriterion("relate_proj_name3 like", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3NotLike(String value) {
			addCriterion("relate_proj_name3 not like", value, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3In(List<String> values) {
			addCriterion("relate_proj_name3 in", values, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3NotIn(List<String> values) {
			addCriterion("relate_proj_name3 not in", values, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3Between(String value1, String value2) {
			addCriterion("relate_proj_name3 between", value1, value2, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andRelateProjName3NotBetween(String value1, String value2) {
			addCriterion("relate_proj_name3 not between", value1, value2, "relateProjName3");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateIsNull() {
			addCriterion("subcontract_state is null");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateIsNotNull() {
			addCriterion("subcontract_state is not null");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateEqualTo(String value) {
			addCriterion("subcontract_state =", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateNotEqualTo(String value) {
			addCriterion("subcontract_state <>", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateGreaterThan(String value) {
			addCriterion("subcontract_state >", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateGreaterThanOrEqualTo(String value) {
			addCriterion("subcontract_state >=", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateLessThan(String value) {
			addCriterion("subcontract_state <", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateLessThanOrEqualTo(String value) {
			addCriterion("subcontract_state <=", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateLike(String value) {
			addCriterion("subcontract_state like", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateNotLike(String value) {
			addCriterion("subcontract_state not like", value, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateIn(List<String> values) {
			addCriterion("subcontract_state in", values, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateNotIn(List<String> values) {
			addCriterion("subcontract_state not in", values, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateBetween(String value1, String value2) {
			addCriterion("subcontract_state between", value1, value2, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andSubcontractStateNotBetween(String value1, String value2) {
			addCriterion("subcontract_state not between", value1, value2, "subcontractState");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIsNull() {
			addCriterion("proj_manager_name is null");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIsNotNull() {
			addCriterion("proj_manager_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameEqualTo(String value) {
			addCriterion("proj_manager_name =", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotEqualTo(String value) {
			addCriterion("proj_manager_name <>", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameGreaterThan(String value) {
			addCriterion("proj_manager_name >", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manager_name >=", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLessThan(String value) {
			addCriterion("proj_manager_name <", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLessThanOrEqualTo(String value) {
			addCriterion("proj_manager_name <=", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameLike(String value) {
			addCriterion("proj_manager_name like", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotLike(String value) {
			addCriterion("proj_manager_name not like", value, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameIn(List<String> values) {
			addCriterion("proj_manager_name in", values, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotIn(List<String> values) {
			addCriterion("proj_manager_name not in", values, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameBetween(String value1, String value2) {
			addCriterion("proj_manager_name between", value1, value2, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManagerNameNotBetween(String value1, String value2) {
			addCriterion("proj_manager_name not between", value1, value2, "projManagerName");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIsNull() {
			addCriterion("proj_manage_id is null");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIsNotNull() {
			addCriterion("proj_manage_id is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageIdEqualTo(String value) {
			addCriterion("proj_manage_id =", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotEqualTo(String value) {
			addCriterion("proj_manage_id <>", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdGreaterThan(String value) {
			addCriterion("proj_manage_id >", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_id >=", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLessThan(String value) {
			addCriterion("proj_manage_id <", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_id <=", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdLike(String value) {
			addCriterion("proj_manage_id like", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotLike(String value) {
			addCriterion("proj_manage_id not like", value, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdIn(List<String> values) {
			addCriterion("proj_manage_id in", values, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotIn(List<String> values) {
			addCriterion("proj_manage_id not in", values, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdBetween(String value1, String value2) {
			addCriterion("proj_manage_id between", value1, value2, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageIdNotBetween(String value1, String value2) {
			addCriterion("proj_manage_id not between", value1, value2, "projManageId");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIsNull() {
			addCriterion("proj_manage_email is null");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIsNotNull() {
			addCriterion("proj_manage_email is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailEqualTo(String value) {
			addCriterion("proj_manage_email =", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotEqualTo(String value) {
			addCriterion("proj_manage_email <>", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailGreaterThan(String value) {
			addCriterion("proj_manage_email >", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_email >=", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLessThan(String value) {
			addCriterion("proj_manage_email <", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_email <=", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailLike(String value) {
			addCriterion("proj_manage_email like", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotLike(String value) {
			addCriterion("proj_manage_email not like", value, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailIn(List<String> values) {
			addCriterion("proj_manage_email in", values, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotIn(List<String> values) {
			addCriterion("proj_manage_email not in", values, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailBetween(String value1, String value2) {
			addCriterion("proj_manage_email between", value1, value2, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageEmailNotBetween(String value1, String value2) {
			addCriterion("proj_manage_email not between", value1, value2, "projManageEmail");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIsNull() {
			addCriterion("proj_manage_tel is null");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIsNotNull() {
			addCriterion("proj_manage_tel is not null");
			return (Criteria) this;
		}

		public Criteria andProjManageTelEqualTo(String value) {
			addCriterion("proj_manage_tel =", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotEqualTo(String value) {
			addCriterion("proj_manage_tel <>", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelGreaterThan(String value) {
			addCriterion("proj_manage_tel >", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manage_tel >=", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLessThan(String value) {
			addCriterion("proj_manage_tel <", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLessThanOrEqualTo(String value) {
			addCriterion("proj_manage_tel <=", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelLike(String value) {
			addCriterion("proj_manage_tel like", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotLike(String value) {
			addCriterion("proj_manage_tel not like", value, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelIn(List<String> values) {
			addCriterion("proj_manage_tel in", values, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotIn(List<String> values) {
			addCriterion("proj_manage_tel not in", values, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelBetween(String value1, String value2) {
			addCriterion("proj_manage_tel between", value1, value2, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManageTelNotBetween(String value1, String value2) {
			addCriterion("proj_manage_tel not between", value1, value2, "projManageTel");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameIsNull() {
			addCriterion("proj_manager_director_name is null");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameIsNotNull() {
			addCriterion("proj_manager_director_name is not null");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameEqualTo(String value) {
			addCriterion("proj_manager_director_name =", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameNotEqualTo(String value) {
			addCriterion("proj_manager_director_name <>", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameGreaterThan(String value) {
			addCriterion("proj_manager_director_name >", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameGreaterThanOrEqualTo(String value) {
			addCriterion("proj_manager_director_name >=", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameLessThan(String value) {
			addCriterion("proj_manager_director_name <", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameLessThanOrEqualTo(String value) {
			addCriterion("proj_manager_director_name <=", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameLike(String value) {
			addCriterion("proj_manager_director_name like", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameNotLike(String value) {
			addCriterion("proj_manager_director_name not like", value, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameIn(List<String> values) {
			addCriterion("proj_manager_director_name in", values, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameNotIn(List<String> values) {
			addCriterion("proj_manager_director_name not in", values, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameBetween(String value1, String value2) {
			addCriterion("proj_manager_director_name between", value1, value2, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjManagerDirectorNameNotBetween(String value1, String value2) {
			addCriterion("proj_manager_director_name not between", value1, value2, "projManagerDirectorName");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1IsNull() {
			addCriterion("proj_backbone1 is null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1IsNotNull() {
			addCriterion("proj_backbone1 is not null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1EqualTo(String value) {
			addCriterion("proj_backbone1 =", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1NotEqualTo(String value) {
			addCriterion("proj_backbone1 <>", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1GreaterThan(String value) {
			addCriterion("proj_backbone1 >", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1GreaterThanOrEqualTo(String value) {
			addCriterion("proj_backbone1 >=", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1LessThan(String value) {
			addCriterion("proj_backbone1 <", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1LessThanOrEqualTo(String value) {
			addCriterion("proj_backbone1 <=", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1Like(String value) {
			addCriterion("proj_backbone1 like", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1NotLike(String value) {
			addCriterion("proj_backbone1 not like", value, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1In(List<String> values) {
			addCriterion("proj_backbone1 in", values, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1NotIn(List<String> values) {
			addCriterion("proj_backbone1 not in", values, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1Between(String value1, String value2) {
			addCriterion("proj_backbone1 between", value1, value2, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone1NotBetween(String value1, String value2) {
			addCriterion("proj_backbone1 not between", value1, value2, "projBackbone1");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2IsNull() {
			addCriterion("proj_backbone2 is null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2IsNotNull() {
			addCriterion("proj_backbone2 is not null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2EqualTo(String value) {
			addCriterion("proj_backbone2 =", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2NotEqualTo(String value) {
			addCriterion("proj_backbone2 <>", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2GreaterThan(String value) {
			addCriterion("proj_backbone2 >", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2GreaterThanOrEqualTo(String value) {
			addCriterion("proj_backbone2 >=", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2LessThan(String value) {
			addCriterion("proj_backbone2 <", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2LessThanOrEqualTo(String value) {
			addCriterion("proj_backbone2 <=", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2Like(String value) {
			addCriterion("proj_backbone2 like", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2NotLike(String value) {
			addCriterion("proj_backbone2 not like", value, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2In(List<String> values) {
			addCriterion("proj_backbone2 in", values, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2NotIn(List<String> values) {
			addCriterion("proj_backbone2 not in", values, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2Between(String value1, String value2) {
			addCriterion("proj_backbone2 between", value1, value2, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone2NotBetween(String value1, String value2) {
			addCriterion("proj_backbone2 not between", value1, value2, "projBackbone2");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3IsNull() {
			addCriterion("proj_backbone3 is null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3IsNotNull() {
			addCriterion("proj_backbone3 is not null");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3EqualTo(String value) {
			addCriterion("proj_backbone3 =", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3NotEqualTo(String value) {
			addCriterion("proj_backbone3 <>", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3GreaterThan(String value) {
			addCriterion("proj_backbone3 >", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3GreaterThanOrEqualTo(String value) {
			addCriterion("proj_backbone3 >=", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3LessThan(String value) {
			addCriterion("proj_backbone3 <", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3LessThanOrEqualTo(String value) {
			addCriterion("proj_backbone3 <=", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3Like(String value) {
			addCriterion("proj_backbone3 like", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3NotLike(String value) {
			addCriterion("proj_backbone3 not like", value, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3In(List<String> values) {
			addCriterion("proj_backbone3 in", values, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3NotIn(List<String> values) {
			addCriterion("proj_backbone3 not in", values, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3Between(String value1, String value2) {
			addCriterion("proj_backbone3 between", value1, value2, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBackbone3NotBetween(String value1, String value2) {
			addCriterion("proj_backbone3 not between", value1, value2, "projBackbone3");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIsNull() {
			addCriterion("proj_begin_date is null");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIsNotNull() {
			addCriterion("proj_begin_date is not null");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateEqualTo(String value) {
			addCriterion("proj_begin_date =", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotEqualTo(String value) {
			addCriterion("proj_begin_date <>", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateGreaterThan(String value) {
			addCriterion("proj_begin_date >", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateGreaterThanOrEqualTo(String value) {
			addCriterion("proj_begin_date >=", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLessThan(String value) {
			addCriterion("proj_begin_date <", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLessThanOrEqualTo(String value) {
			addCriterion("proj_begin_date <=", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateLike(String value) {
			addCriterion("proj_begin_date like", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotLike(String value) {
			addCriterion("proj_begin_date not like", value, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateIn(List<String> values) {
			addCriterion("proj_begin_date in", values, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotIn(List<String> values) {
			addCriterion("proj_begin_date not in", values, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateBetween(String value1, String value2) {
			addCriterion("proj_begin_date between", value1, value2, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjBeginDateNotBetween(String value1, String value2) {
			addCriterion("proj_begin_date not between", value1, value2, "projBeginDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIsNull() {
			addCriterion("proj_end_date is null");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIsNotNull() {
			addCriterion("proj_end_date is not null");
			return (Criteria) this;
		}

		public Criteria andProjEndDateEqualTo(String value) {
			addCriterion("proj_end_date =", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotEqualTo(String value) {
			addCriterion("proj_end_date <>", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateGreaterThan(String value) {
			addCriterion("proj_end_date >", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateGreaterThanOrEqualTo(String value) {
			addCriterion("proj_end_date >=", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLessThan(String value) {
			addCriterion("proj_end_date <", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLessThanOrEqualTo(String value) {
			addCriterion("proj_end_date <=", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateLike(String value) {
			addCriterion("proj_end_date like", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotLike(String value) {
			addCriterion("proj_end_date not like", value, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateIn(List<String> values) {
			addCriterion("proj_end_date in", values, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotIn(List<String> values) {
			addCriterion("proj_end_date not in", values, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateBetween(String value1, String value2) {
			addCriterion("proj_end_date between", value1, value2, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andProjEndDateNotBetween(String value1, String value2) {
			addCriterion("proj_end_date not between", value1, value2, "projEndDate");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNull() {
			addCriterion("input_date is null");
			return (Criteria) this;
		}

		public Criteria andInputDateIsNotNull() {
			addCriterion("input_date is not null");
			return (Criteria) this;
		}

		public Criteria andInputDateEqualTo(String value) {
			addCriterion("input_date =", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotEqualTo(String value) {
			addCriterion("input_date <>", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThan(String value) {
			addCriterion("input_date >", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateGreaterThanOrEqualTo(String value) {
			addCriterion("input_date >=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThan(String value) {
			addCriterion("input_date <", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLessThanOrEqualTo(String value) {
			addCriterion("input_date <=", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateLike(String value) {
			addCriterion("input_date like", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotLike(String value) {
			addCriterion("input_date not like", value, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateIn(List<String> values) {
			addCriterion("input_date in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotIn(List<String> values) {
			addCriterion("input_date not in", values, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateBetween(String value1, String value2) {
			addCriterion("input_date between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andInputDateNotBetween(String value1, String value2) {
			addCriterion("input_date not between", value1, value2, "inputDate");
			return (Criteria) this;
		}

		public Criteria andProjStateIsNull() {
			addCriterion("proj_state is null");
			return (Criteria) this;
		}

		public Criteria andProjStateIsNotNull() {
			addCriterion("proj_state is not null");
			return (Criteria) this;
		}

		public Criteria andProjStateEqualTo(String value) {
			addCriterion("proj_state =", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateNotEqualTo(String value) {
			addCriterion("proj_state <>", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateGreaterThan(String value) {
			addCriterion("proj_state >", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateGreaterThanOrEqualTo(String value) {
			addCriterion("proj_state >=", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateLessThan(String value) {
			addCriterion("proj_state <", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateLessThanOrEqualTo(String value) {
			addCriterion("proj_state <=", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateLike(String value) {
			addCriterion("proj_state like", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateNotLike(String value) {
			addCriterion("proj_state not like", value, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateIn(List<String> values) {
			addCriterion("proj_state in", values, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateNotIn(List<String> values) {
			addCriterion("proj_state not in", values, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateBetween(String value1, String value2) {
			addCriterion("proj_state between", value1, value2, "projState");
			return (Criteria) this;
		}

		public Criteria andProjStateNotBetween(String value1, String value2) {
			addCriterion("proj_state not between", value1, value2, "projState");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1IsNull() {
			addCriterion("business_tech_key1 is null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1IsNotNull() {
			addCriterion("business_tech_key1 is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1EqualTo(String value) {
			addCriterion("business_tech_key1 =", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1NotEqualTo(String value) {
			addCriterion("business_tech_key1 <>", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1GreaterThan(String value) {
			addCriterion("business_tech_key1 >", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1GreaterThanOrEqualTo(String value) {
			addCriterion("business_tech_key1 >=", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1LessThan(String value) {
			addCriterion("business_tech_key1 <", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1LessThanOrEqualTo(String value) {
			addCriterion("business_tech_key1 <=", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1Like(String value) {
			addCriterion("business_tech_key1 like", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1NotLike(String value) {
			addCriterion("business_tech_key1 not like", value, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1In(List<String> values) {
			addCriterion("business_tech_key1 in", values, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1NotIn(List<String> values) {
			addCriterion("business_tech_key1 not in", values, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1Between(String value1, String value2) {
			addCriterion("business_tech_key1 between", value1, value2, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey1NotBetween(String value1, String value2) {
			addCriterion("business_tech_key1 not between", value1, value2, "businessTechKey1");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2IsNull() {
			addCriterion("business_tech_key2 is null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2IsNotNull() {
			addCriterion("business_tech_key2 is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2EqualTo(String value) {
			addCriterion("business_tech_key2 =", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2NotEqualTo(String value) {
			addCriterion("business_tech_key2 <>", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2GreaterThan(String value) {
			addCriterion("business_tech_key2 >", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2GreaterThanOrEqualTo(String value) {
			addCriterion("business_tech_key2 >=", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2LessThan(String value) {
			addCriterion("business_tech_key2 <", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2LessThanOrEqualTo(String value) {
			addCriterion("business_tech_key2 <=", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2Like(String value) {
			addCriterion("business_tech_key2 like", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2NotLike(String value) {
			addCriterion("business_tech_key2 not like", value, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2In(List<String> values) {
			addCriterion("business_tech_key2 in", values, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2NotIn(List<String> values) {
			addCriterion("business_tech_key2 not in", values, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2Between(String value1, String value2) {
			addCriterion("business_tech_key2 between", value1, value2, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey2NotBetween(String value1, String value2) {
			addCriterion("business_tech_key2 not between", value1, value2, "businessTechKey2");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3IsNull() {
			addCriterion("business_tech_key3 is null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3IsNotNull() {
			addCriterion("business_tech_key3 is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3EqualTo(String value) {
			addCriterion("business_tech_key3 =", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3NotEqualTo(String value) {
			addCriterion("business_tech_key3 <>", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3GreaterThan(String value) {
			addCriterion("business_tech_key3 >", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3GreaterThanOrEqualTo(String value) {
			addCriterion("business_tech_key3 >=", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3LessThan(String value) {
			addCriterion("business_tech_key3 <", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3LessThanOrEqualTo(String value) {
			addCriterion("business_tech_key3 <=", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3Like(String value) {
			addCriterion("business_tech_key3 like", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3NotLike(String value) {
			addCriterion("business_tech_key3 not like", value, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3In(List<String> values) {
			addCriterion("business_tech_key3 in", values, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3NotIn(List<String> values) {
			addCriterion("business_tech_key3 not in", values, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3Between(String value1, String value2) {
			addCriterion("business_tech_key3 between", value1, value2, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessTechKey3NotBetween(String value1, String value2) {
			addCriterion("business_tech_key3 not between", value1, value2, "businessTechKey3");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefIsNull() {
			addCriterion("business_brief is null");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefIsNotNull() {
			addCriterion("business_brief is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefEqualTo(String value) {
			addCriterion("business_brief =", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefNotEqualTo(String value) {
			addCriterion("business_brief <>", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefGreaterThan(String value) {
			addCriterion("business_brief >", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefGreaterThanOrEqualTo(String value) {
			addCriterion("business_brief >=", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefLessThan(String value) {
			addCriterion("business_brief <", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefLessThanOrEqualTo(String value) {
			addCriterion("business_brief <=", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefLike(String value) {
			addCriterion("business_brief like", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefNotLike(String value) {
			addCriterion("business_brief not like", value, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefIn(List<String> values) {
			addCriterion("business_brief in", values, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefNotIn(List<String> values) {
			addCriterion("business_brief not in", values, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefBetween(String value1, String value2) {
			addCriterion("business_brief between", value1, value2, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessBriefNotBetween(String value1, String value2) {
			addCriterion("business_brief not between", value1, value2, "businessBrief");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncIsNull() {
			addCriterion("business_func is null");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncIsNotNull() {
			addCriterion("business_func is not null");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncEqualTo(String value) {
			addCriterion("business_func =", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncNotEqualTo(String value) {
			addCriterion("business_func <>", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncGreaterThan(String value) {
			addCriterion("business_func >", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncGreaterThanOrEqualTo(String value) {
			addCriterion("business_func >=", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncLessThan(String value) {
			addCriterion("business_func <", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncLessThanOrEqualTo(String value) {
			addCriterion("business_func <=", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncLike(String value) {
			addCriterion("business_func like", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncNotLike(String value) {
			addCriterion("business_func not like", value, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncIn(List<String> values) {
			addCriterion("business_func in", values, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncNotIn(List<String> values) {
			addCriterion("business_func not in", values, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncBetween(String value1, String value2) {
			addCriterion("business_func between", value1, value2, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andBusinessFuncNotBetween(String value1, String value2) {
			addCriterion("business_func not between", value1, value2, "businessFunc");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexIsNull() {
			addCriterion("performance_index is null");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexIsNotNull() {
			addCriterion("performance_index is not null");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexEqualTo(String value) {
			addCriterion("performance_index =", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexNotEqualTo(String value) {
			addCriterion("performance_index <>", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexGreaterThan(String value) {
			addCriterion("performance_index >", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexGreaterThanOrEqualTo(String value) {
			addCriterion("performance_index >=", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexLessThan(String value) {
			addCriterion("performance_index <", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexLessThanOrEqualTo(String value) {
			addCriterion("performance_index <=", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexLike(String value) {
			addCriterion("performance_index like", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexNotLike(String value) {
			addCriterion("performance_index not like", value, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexIn(List<String> values) {
			addCriterion("performance_index in", values, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexNotIn(List<String> values) {
			addCriterion("performance_index not in", values, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexBetween(String value1, String value2) {
			addCriterion("performance_index between", value1, value2, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andPerformanceIndexNotBetween(String value1, String value2) {
			addCriterion("performance_index not between", value1, value2, "performanceIndex");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIsNull() {
			addCriterion("system_soft is null");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIsNotNull() {
			addCriterion("system_soft is not null");
			return (Criteria) this;
		}

		public Criteria andSystemSoftEqualTo(String value) {
			addCriterion("system_soft =", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotEqualTo(String value) {
			addCriterion("system_soft <>", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftGreaterThan(String value) {
			addCriterion("system_soft >", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftGreaterThanOrEqualTo(String value) {
			addCriterion("system_soft >=", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLessThan(String value) {
			addCriterion("system_soft <", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLessThanOrEqualTo(String value) {
			addCriterion("system_soft <=", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftLike(String value) {
			addCriterion("system_soft like", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotLike(String value) {
			addCriterion("system_soft not like", value, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftIn(List<String> values) {
			addCriterion("system_soft in", values, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotIn(List<String> values) {
			addCriterion("system_soft not in", values, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftBetween(String value1, String value2) {
			addCriterion("system_soft between", value1, value2, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemSoftNotBetween(String value1, String value2) {
			addCriterion("system_soft not between", value1, value2, "systemSoft");
			return (Criteria) this;
		}

		public Criteria andSystemHardIsNull() {
			addCriterion("system_hard is null");
			return (Criteria) this;
		}

		public Criteria andSystemHardIsNotNull() {
			addCriterion("system_hard is not null");
			return (Criteria) this;
		}

		public Criteria andSystemHardEqualTo(String value) {
			addCriterion("system_hard =", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotEqualTo(String value) {
			addCriterion("system_hard <>", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardGreaterThan(String value) {
			addCriterion("system_hard >", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardGreaterThanOrEqualTo(String value) {
			addCriterion("system_hard >=", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLessThan(String value) {
			addCriterion("system_hard <", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLessThanOrEqualTo(String value) {
			addCriterion("system_hard <=", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardLike(String value) {
			addCriterion("system_hard like", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotLike(String value) {
			addCriterion("system_hard not like", value, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardIn(List<String> values) {
			addCriterion("system_hard in", values, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotIn(List<String> values) {
			addCriterion("system_hard not in", values, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardBetween(String value1, String value2) {
			addCriterion("system_hard between", value1, value2, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemHardNotBetween(String value1, String value2) {
			addCriterion("system_hard not between", value1, value2, "systemHard");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecIsNull() {
			addCriterion("system_architec is null");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecIsNotNull() {
			addCriterion("system_architec is not null");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecEqualTo(String value) {
			addCriterion("system_architec =", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecNotEqualTo(String value) {
			addCriterion("system_architec <>", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecGreaterThan(String value) {
			addCriterion("system_architec >", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecGreaterThanOrEqualTo(String value) {
			addCriterion("system_architec >=", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecLessThan(String value) {
			addCriterion("system_architec <", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecLessThanOrEqualTo(String value) {
			addCriterion("system_architec <=", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecLike(String value) {
			addCriterion("system_architec like", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecNotLike(String value) {
			addCriterion("system_architec not like", value, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecIn(List<String> values) {
			addCriterion("system_architec in", values, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecNotIn(List<String> values) {
			addCriterion("system_architec not in", values, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecBetween(String value1, String value2) {
			addCriterion("system_architec between", value1, value2, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andSystemArchitecNotBetween(String value1, String value2) {
			addCriterion("system_architec not between", value1, value2, "systemArchitec");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardIsNull() {
			addCriterion("relavent_standard is null");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardIsNotNull() {
			addCriterion("relavent_standard is not null");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardEqualTo(String value) {
			addCriterion("relavent_standard =", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardNotEqualTo(String value) {
			addCriterion("relavent_standard <>", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardGreaterThan(String value) {
			addCriterion("relavent_standard >", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardGreaterThanOrEqualTo(String value) {
			addCriterion("relavent_standard >=", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardLessThan(String value) {
			addCriterion("relavent_standard <", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardLessThanOrEqualTo(String value) {
			addCriterion("relavent_standard <=", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardLike(String value) {
			addCriterion("relavent_standard like", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardNotLike(String value) {
			addCriterion("relavent_standard not like", value, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardIn(List<String> values) {
			addCriterion("relavent_standard in", values, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardNotIn(List<String> values) {
			addCriterion("relavent_standard not in", values, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardBetween(String value1, String value2) {
			addCriterion("relavent_standard between", value1, value2, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andRelaventStandardNotBetween(String value1, String value2) {
			addCriterion("relavent_standard not between", value1, value2, "relaventStandard");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIsNull() {
			addCriterion("key_tech_skills is null");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIsNotNull() {
			addCriterion("key_tech_skills is not null");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsEqualTo(String value) {
			addCriterion("key_tech_skills =", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotEqualTo(String value) {
			addCriterion("key_tech_skills <>", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsGreaterThan(String value) {
			addCriterion("key_tech_skills >", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsGreaterThanOrEqualTo(String value) {
			addCriterion("key_tech_skills >=", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLessThan(String value) {
			addCriterion("key_tech_skills <", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLessThanOrEqualTo(String value) {
			addCriterion("key_tech_skills <=", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsLike(String value) {
			addCriterion("key_tech_skills like", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotLike(String value) {
			addCriterion("key_tech_skills not like", value, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsIn(List<String> values) {
			addCriterion("key_tech_skills in", values, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotIn(List<String> values) {
			addCriterion("key_tech_skills not in", values, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsBetween(String value1, String value2) {
			addCriterion("key_tech_skills between", value1, value2, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andKeyTechSkillsNotBetween(String value1, String value2) {
			addCriterion("key_tech_skills not between", value1, value2, "keyTechSkills");
			return (Criteria) this;
		}

		public Criteria andUsetoolsIsNull() {
			addCriterion("usetools is null");
			return (Criteria) this;
		}

		public Criteria andUsetoolsIsNotNull() {
			addCriterion("usetools is not null");
			return (Criteria) this;
		}

		public Criteria andUsetoolsEqualTo(String value) {
			addCriterion("usetools =", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsNotEqualTo(String value) {
			addCriterion("usetools <>", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsGreaterThan(String value) {
			addCriterion("usetools >", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsGreaterThanOrEqualTo(String value) {
			addCriterion("usetools >=", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsLessThan(String value) {
			addCriterion("usetools <", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsLessThanOrEqualTo(String value) {
			addCriterion("usetools <=", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsLike(String value) {
			addCriterion("usetools like", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsNotLike(String value) {
			addCriterion("usetools not like", value, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsIn(List<String> values) {
			addCriterion("usetools in", values, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsNotIn(List<String> values) {
			addCriterion("usetools not in", values, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsBetween(String value1, String value2) {
			addCriterion("usetools between", value1, value2, "usetools");
			return (Criteria) this;
		}

		public Criteria andUsetoolsNotBetween(String value1, String value2) {
			addCriterion("usetools not between", value1, value2, "usetools");
			return (Criteria) this;
		}

		public Criteria andRemainingProbIsNull() {
			addCriterion("remaining_prob is null");
			return (Criteria) this;
		}

		public Criteria andRemainingProbIsNotNull() {
			addCriterion("remaining_prob is not null");
			return (Criteria) this;
		}

		public Criteria andRemainingProbEqualTo(String value) {
			addCriterion("remaining_prob =", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbNotEqualTo(String value) {
			addCriterion("remaining_prob <>", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbGreaterThan(String value) {
			addCriterion("remaining_prob >", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbGreaterThanOrEqualTo(String value) {
			addCriterion("remaining_prob >=", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbLessThan(String value) {
			addCriterion("remaining_prob <", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbLessThanOrEqualTo(String value) {
			addCriterion("remaining_prob <=", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbLike(String value) {
			addCriterion("remaining_prob like", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbNotLike(String value) {
			addCriterion("remaining_prob not like", value, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbIn(List<String> values) {
			addCriterion("remaining_prob in", values, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbNotIn(List<String> values) {
			addCriterion("remaining_prob not in", values, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbBetween(String value1, String value2) {
			addCriterion("remaining_prob between", value1, value2, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andRemainingProbNotBetween(String value1, String value2) {
			addCriterion("remaining_prob not between", value1, value2, "remainingProb");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiIsNull() {
			addCriterion("market_competi is null");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiIsNotNull() {
			addCriterion("market_competi is not null");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiEqualTo(String value) {
			addCriterion("market_competi =", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiNotEqualTo(String value) {
			addCriterion("market_competi <>", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiGreaterThan(String value) {
			addCriterion("market_competi >", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiGreaterThanOrEqualTo(String value) {
			addCriterion("market_competi >=", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiLessThan(String value) {
			addCriterion("market_competi <", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiLessThanOrEqualTo(String value) {
			addCriterion("market_competi <=", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiLike(String value) {
			addCriterion("market_competi like", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiNotLike(String value) {
			addCriterion("market_competi not like", value, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiIn(List<String> values) {
			addCriterion("market_competi in", values, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiNotIn(List<String> values) {
			addCriterion("market_competi not in", values, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiBetween(String value1, String value2) {
			addCriterion("market_competi between", value1, value2, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andMarketCompetiNotBetween(String value1, String value2) {
			addCriterion("market_competi not between", value1, value2, "marketCompeti");
			return (Criteria) this;
		}

		public Criteria andConstraintDependIsNull() {
			addCriterion("constraint_depend is null");
			return (Criteria) this;
		}

		public Criteria andConstraintDependIsNotNull() {
			addCriterion("constraint_depend is not null");
			return (Criteria) this;
		}

		public Criteria andConstraintDependEqualTo(String value) {
			addCriterion("constraint_depend =", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependNotEqualTo(String value) {
			addCriterion("constraint_depend <>", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependGreaterThan(String value) {
			addCriterion("constraint_depend >", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependGreaterThanOrEqualTo(String value) {
			addCriterion("constraint_depend >=", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependLessThan(String value) {
			addCriterion("constraint_depend <", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependLessThanOrEqualTo(String value) {
			addCriterion("constraint_depend <=", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependLike(String value) {
			addCriterion("constraint_depend like", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependNotLike(String value) {
			addCriterion("constraint_depend not like", value, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependIn(List<String> values) {
			addCriterion("constraint_depend in", values, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependNotIn(List<String> values) {
			addCriterion("constraint_depend not in", values, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependBetween(String value1, String value2) {
			addCriterion("constraint_depend between", value1, value2, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andConstraintDependNotBetween(String value1, String value2) {
			addCriterion("constraint_depend not between", value1, value2, "constraintDepend");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3IsNull() {
			addCriterion("proj_back_bone3 is null");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3IsNotNull() {
			addCriterion("proj_back_bone3 is not null");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3EqualTo(String value) {
			addCriterion("proj_back_bone3 =", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3NotEqualTo(String value) {
			addCriterion("proj_back_bone3 <>", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3GreaterThan(String value) {
			addCriterion("proj_back_bone3 >", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3GreaterThanOrEqualTo(String value) {
			addCriterion("proj_back_bone3 >=", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3LessThan(String value) {
			addCriterion("proj_back_bone3 <", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3LessThanOrEqualTo(String value) {
			addCriterion("proj_back_bone3 <=", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3Like(String value) {
			addCriterion("proj_back_bone3 like", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3NotLike(String value) {
			addCriterion("proj_back_bone3 not like", value, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3In(List<String> values) {
			addCriterion("proj_back_bone3 in", values, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3NotIn(List<String> values) {
			addCriterion("proj_back_bone3 not in", values, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3Between(String value1, String value2) {
			addCriterion("proj_back_bone3 between", value1, value2, "projBackBone3");
			return (Criteria) this;
		}

		public Criteria andProjBackBone3NotBetween(String value1, String value2) {
			addCriterion("proj_back_bone3 not between", value1, value2, "projBackBone3");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_projdigest_old
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}