package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TApplication;
import com.chinasofti.projectDigest.pojo.TApplicationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TApplicationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	long countByExample(TApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int deleteByExample(TApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int insert(TApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int insertSelective(TApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	List<TApplication> selectByExample(TApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	TApplication selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TApplication record, @Param("example") TApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TApplication record, @Param("example") TApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_application
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TApplication record);

	int insert2(TApplication record);
}