package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TField;
import com.chinasofti.projectDigest.pojo.TFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TFieldMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	long countByExample(TFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int deleteByExample(TFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int insert(TField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int insertSelective(TField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	List<TField> selectByExample(TFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	TField selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TField record, @Param("example") TFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TField record, @Param("example") TFieldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TField record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_field
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TField record);

	int insert2(TField record);

}