package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TIndustry;
import com.chinasofti.projectDigest.pojo.TIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TIndustryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	long countByExample(TIndustryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int deleteByExample(TIndustryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int insert(TIndustry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int insertSelective(TIndustry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	List<TIndustry> selectByExample(TIndustryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	TIndustry selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TIndustry record, @Param("example") TIndustryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TIndustry record, @Param("example") TIndustryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TIndustry record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_industry
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TIndustry record);

	int insert2(TIndustry record);

	
}