package com.chinasofti.projectDigest.dao;

import com.chinasofti.projectDigest.pojo.TProjdigest;
import com.chinasofti.projectDigest.pojo.TProjdigestOld;
import com.chinasofti.projectDigest.pojo.TProjdigestOldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TProjdigestOldMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	long countByExample(TProjdigestOldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int deleteByExample(TProjdigestOldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int insert(TProjdigestOld record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int insertSelective(TProjdigestOld record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	List<TProjdigestOld> selectByExample(TProjdigestOldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	TProjdigestOld selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TProjdigestOld record,
			@Param("example") TProjdigestOldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TProjdigestOld record, @Param("example") TProjdigestOldExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TProjdigestOld record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_projdigest_old
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TProjdigestOld record);

	//insert by useGeneratedKeys
    int insert2(TProjdigestOld record);
    
    //insert by selectKey(after)
    int insert3(TProjdigestOld record);
    
    List<TProjdigestOld> getAll();
}